server=http://localhost:4111
apiVersion=/api/v1
admin.auth=Basic YWRtaW46YWRtaW4=
default.password=VeryStrongPassword33$

uiUrl=http://host.docker.internal:3000

browser=chrome
browser.size=1920x1080
browser.timeout=10000
page.load.timeout=60000

selenoid.enabled=true
selenoid.url=http://localhost:4444/wd/hub

admin.username=admin
admin.password=admin

db.url=jdbc:postgresql://localhost:5433/nbank
db.username=postgres
db.password=postgres